// ********************************************************
// Copyright (C) 2021 Louis S. Berman (louis@squideyes.com) 
// 
// This file is part of SquidEyes.Trading
// 
// The use of this source code is licensed under the terms 
// of the MIT License (https://opensource.org/licenses/MIT)
// ********************************************************

namespace SquidEyes.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SquidEyes.UnitTests.Properties.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/05/2020 17:00:22.039,1.11656,1.11687
        ///01/05/2020 17:00:32.758,1.11656,1.11703
        ///01/05/2020 17:00:44.561,1.11656,1.11694
        ///01/05/2020 17:00:45.913,1.11656,1.11690
        ///01/05/2020 17:00:46.027,1.11667,1.11690
        ///01/05/2020 17:02:05.351,1.11666,1.11690
        ///01/05/2020 17:02:08.457,1.11666,1.11688
        ///01/05/2020 17:02:08.558,1.11666,1.11690
        ///01/05/2020 17:02:08.709,1.11666,1.11691
        ///01/05/2020 17:02:12.392,1.11665,1.11678
        ///01/05/2020 17:02:23.080,1.11664,1.11678
        ///01/05/2020 17:02:38.506,1.11664,1.11677
        ///01/05/2020 17:02:46. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DC_EURUSD_20200106_EST_CSV {
            get {
                return ResourceManager.GetString("DC_EURUSD_20200106_EST_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DC_EURUSD_20200106_EST_STS {
            get {
                object obj = ResourceManager.GetObject("DC_EURUSD_20200106_EST_STS", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
