//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquidEyes.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SquidEyes.UnitTests.Properties.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/05/2020 17:00:22.039,1.11656,1.11687
        ///01/05/2020 17:00:32.758,1.11656,1.11703
        ///01/05/2020 17:00:44.561,1.11656,1.11694
        ///01/05/2020 17:00:45.913,1.11656,1.11690
        ///01/05/2020 17:00:46.027,1.11667,1.11690
        ///01/05/2020 17:02:05.351,1.11666,1.11690
        ///01/05/2020 17:02:08.457,1.11666,1.11689
        ///01/05/2020 17:02:08.558,1.11666,1.11690
        ///01/05/2020 17:02:08.709,1.11666,1.11691
        ///01/05/2020 17:02:12.392,1.11665,1.11678
        ///01/05/2020 17:02:23.080,1.11664,1.11678
        ///01/05/2020 17:02:38.506,1.11664,1.11677
        ///01/05/2020 17:02:46. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DC_EURUSD_20200106_EST_CSV {
            get {
                return ResourceManager.GetString("DC_EURUSD_20200106_EST_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DC_EURUSD_20200106_EST_STS {
            get {
                object obj = ResourceManager.GetObject("DC_EURUSD_20200106_EST_STS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/06/2020 17:00:00.066,1.11960,1.11980
        ///01/06/2020 17:00:00.204,1.11935,1.11980
        ///01/06/2020 17:00:01.027,1.11928,1.11980
        ///01/06/2020 17:00:01.270,1.11928,1.11973
        ///01/06/2020 17:00:01.790,1.11928,1.11966
        ///01/06/2020 17:00:02.570,1.11928,1.11965
        ///01/06/2020 17:00:02.709,1.11931,1.11966
        ///01/06/2020 17:00:02.760,1.11928,1.11966
        ///01/06/2020 17:00:02.811,1.11928,1.11977
        ///01/06/2020 17:00:02.861,1.11928,1.11969
        ///01/06/2020 17:00:03.060,1.11930,1.11969
        ///01/06/2020 17:00:03.270,1.11928,1.11969
        ///01/06/2020 17:00:03. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DC_EURUSD_20200107_EST_CSV {
            get {
                return ResourceManager.GetString("DC_EURUSD_20200107_EST_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DC_EURUSD_20200107_EST_STS {
            get {
                object obj = ResourceManager.GetObject("DC_EURUSD_20200107_EST_STS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/07/2020 17:00:00.483,1.11529,1.11543
        ///01/07/2020 17:00:00.534,1.11529,1.11545
        ///01/07/2020 17:00:01.068,1.11527,1.11543
        ///01/07/2020 17:00:02.357,1.11527,1.11540
        ///01/07/2020 17:00:02.408,1.11513,1.11523
        ///01/07/2020 17:00:02.519,1.11514,1.11523
        ///01/07/2020 17:00:02.782,1.11514,1.11519
        ///01/07/2020 17:00:03.572,1.11523,1.11530
        ///01/07/2020 17:00:03.623,1.11523,1.11540
        ///01/07/2020 17:00:03.991,1.11524,1.11540
        ///01/07/2020 17:00:04.437,1.11527,1.11540
        ///01/07/2020 17:00:04.538,1.11527,1.11539
        ///01/07/2020 17:00:07. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DC_EURUSD_20200108_EST_CSV {
            get {
                return ResourceManager.GetString("DC_EURUSD_20200108_EST_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DC_EURUSD_20200108_EST_STS {
            get {
                object obj = ResourceManager.GetObject("DC_EURUSD_20200108_EST_STS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DC_EURUSD_20200109_EST_STS {
            get {
                object obj = ResourceManager.GetObject("DC_EURUSD_20200109_EST_STS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/08/2020 17:00:00.001,1.11053,1.11059
        ///01/08/2020 17:00:00.102,1.11049,1.11059
        ///01/08/2020 17:00:00.203,1.11049,1.11060
        ///01/08/2020 17:00:00.498,1.11049,1.11061
        ///01/08/2020 17:00:01.794,1.11053,1.11061
        ///01/08/2020 17:00:02.445,1.11055,1.11061
        ///01/08/2020 17:00:03.240,1.11054,1.11061
        ///01/08/2020 17:00:03.598,1.11055,1.11061
        ///01/08/2020 17:00:04.098,1.11053,1.11061
        ///01/08/2020 17:00:04.227,1.11052,1.11061
        ///01/08/2020 17:00:04.327,1.11049,1.11061
        ///01/08/2020 17:00:05.261,1.11054,1.11061
        ///01/08/2020 17:00:06. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DC_EURUSD_20200109_ESTCSV {
            get {
                return ResourceManager.GetString("DC_EURUSD_20200109_ESTCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DC_EURUSD_20200110_EST_STS {
            get {
                object obj = ResourceManager.GetObject("DC_EURUSD_20200110_EST_STS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/09/2020 17:00:00.168,1.11051,1.11068
        ///01/09/2020 17:00:01.713,1.11049,1.11066
        ///01/09/2020 17:00:03.883,1.11050,1.11065
        ///01/09/2020 17:00:04.156,1.11049,1.11066
        ///01/09/2020 17:00:11.932,1.11052,1.11063
        ///01/09/2020 17:00:18.081,1.11039,1.11050
        ///01/09/2020 17:00:18.732,1.11040,1.11049
        ///01/09/2020 17:00:19.338,1.11039,1.11050
        ///01/09/2020 17:00:55.825,1.11030,1.11081
        ///01/09/2020 17:00:59.393,1.11043,1.11057
        ///01/09/2020 17:02:00.892,1.11045,1.11057
        ///01/09/2020 17:02:04.047,1.11045,1.11056
        ///01/09/2020 17:02:16. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DC_EURUSD_20200110_ESTCSV {
            get {
                return ResourceManager.GetString("DC_EURUSD_20200110_ESTCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WickoCandles {
            get {
                return ResourceManager.GetString("WickoCandles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string WickoTicks {
            get {
                return ResourceManager.GetString("WickoTicks", resourceCulture);
            }
        }
    }
}
